//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica18
{
    using System;
    using System.Collections.Generic;
    
    public partial class FP
    {
        public int Номер { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Команда { get; set; }
        public int СыгранныхСезонов { get; set; }
        public Nullable<int> ЧислоЗаброшенныхШайб { get; set; }
        public Nullable<int> КолГолевыхПередач { get; set; }
        public Nullable<int> ШтрафВремя { get; set; }
        public Nullable<int> КолСыгранныхМатчей { get; set; }
    }
}
